2023-12-25 05:50:12 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: website1_nevadaepro)
2023-12-25 05:50:12 [scrapy.utils.log] INFO: Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 20.0.1 (OpenSSL 1.1.1w  11 Sep 2023), cryptography 3.3.1, Platform Windows-10-10.0.22621-SP0
2023-12-25 05:50:12 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'website1_nevadaepro',
 'LOG_FILE': 'scrapy.log',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'website1_nevadaepro.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['website1_nevadaepro.spiders']}
2023-12-25 05:50:12 [scrapy.extensions.telnet] INFO: Telnet Password: 23d17ab53221a816
2023-12-25 05:50:12 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2023-12-25 05:50:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy_selenium.SeleniumMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2023-12-25 05:50:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2023-12-25 05:50:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2023-12-25 05:50:13 [scrapy.core.engine] INFO: Spider opened
2023-12-25 05:50:13 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-12-25 05:50:13 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2023-12-25 05:50:39 [scrapy.core.engine] INFO: Closing spider (finished)
2023-12-25 05:50:41 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 15370,
 'downloader/request_count': 32,
 'downloader/request_method_count/GET': 32,
 'downloader/response_bytes': 388728,
 'downloader/response_count': 32,
 'downloader/response_status_count/200': 30,
 'downloader/response_status_count/301': 1,
 'downloader/response_status_count/302': 1,
 'elapsed_time_seconds': 25.500323,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 12, 25, 0, 20, 39, 483086),
 'item_scraped_count': 29,
 'log_count/INFO': 10,
 'response_received_count': 30,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 29,
 'scheduler/dequeued/memory': 29,
 'scheduler/enqueued': 29,
 'scheduler/enqueued/memory': 29,
 'start_time': datetime.datetime(2023, 12, 25, 0, 20, 13, 982763)}
2023-12-25 05:50:41 [scrapy.core.engine] INFO: Spider closed (finished)
2023-12-25 05:51:22 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: website1_nevadaepro)
2023-12-25 05:51:22 [scrapy.utils.log] INFO: Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 20.0.1 (OpenSSL 1.1.1w  11 Sep 2023), cryptography 3.3.1, Platform Windows-10-10.0.22621-SP0
2023-12-25 05:51:44 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: website1_nevadaepro)
2023-12-25 05:51:44 [scrapy.utils.log] INFO: Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 20.0.1 (OpenSSL 1.1.1w  11 Sep 2023), cryptography 3.3.1, Platform Windows-10-10.0.22621-SP0
2023-12-25 05:51:44 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'website1_nevadaepro',
 'LOG_FILE': 'scrapy.log',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'website1_nevadaepro.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['website1_nevadaepro.spiders']}
2023-12-25 05:51:44 [scrapy.extensions.telnet] INFO: Telnet Password: 29503a9a849890ee
2023-12-25 05:51:44 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2023-12-25 05:51:45 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy_selenium.SeleniumMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2023-12-25 05:51:45 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2023-12-25 05:51:45 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2023-12-25 05:51:56 [scrapy.crawler] INFO: Received SIGINT, shutting down gracefully. Send again to force 
2023-12-25 05:51:56 [scrapy.crawler] INFO: Received SIGINT twice, forcing unclean shutdown
2023-12-25 05:51:59 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018643D821F0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/25c7229a37a6aee65e0f60a8f4026146/element
2023-12-25 05:52:01 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018643D82E80>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/25c7229a37a6aee65e0f60a8f4026146/element
2023-12-25 05:52:03 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018643DAF040>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/25c7229a37a6aee65e0f60a8f4026146/element
2023-12-25 05:52:07 [urllib3.connectionpool] WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018643DAF3D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/25c7229a37a6aee65e0f60a8f4026146/url
2023-12-25 05:52:09 [urllib3.connectionpool] WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018643DAF580>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/25c7229a37a6aee65e0f60a8f4026146/url
2023-12-25 05:52:11 [urllib3.connectionpool] WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018643DAF700>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session/25c7229a37a6aee65e0f60a8f4026146/url
2023-12-25 05:52:13 [twisted] CRITICAL: Unhandled error in Deferred:
2023-12-25 05:52:13 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connection.py", line 200, in connect
    conn = self._new_conn()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000018643DAF1C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shubh\catalyst\website1_nevadaepro\website1_nevadaepro\spiders\nevadaepro_download_files.py", line 44, in start_requests
    button = driver.find_element_by_xpath(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=53733): Max retries exceeded with url: /session/25c7229a37a6aee65e0f60a8f4026146/element (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018643DAF1C0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\util\connection.py", line 96, in create_connection
    raise err
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\util\connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connection.py", line 200, in connect
    conn = self._new_conn()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000018643DAF880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\scrapy\crawler.py", line 88, in crawl
    start_requests = iter(self.spider.start_requests())
  File "C:\Users\shubh\catalyst\website1_nevadaepro\website1_nevadaepro\spiders\nevadaepro_download_files.py", line 54, in start_requests
    print(driver.current_url + "has no attachments")
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 669, in current_url
    return self.execute(Command.GET_CURRENT_URL)['value']
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\request.py", line 74, in request
    return self.request_encode_url(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\request.py", line 96, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 783, in urlopen
    return self.urlopen(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\util\retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='127.0.0.1', port=53733): Max retries exceeded with url: /session/25c7229a37a6aee65e0f60a8f4026146/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000018643DAF880>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it'))
2023-12-25 05:55:12 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: website1_nevadaepro)
2023-12-25 05:55:12 [scrapy.utils.log] INFO: Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 20.0.1 (OpenSSL 1.1.1w  11 Sep 2023), cryptography 3.3.1, Platform Windows-10-10.0.22621-SP0
2023-12-25 05:55:12 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'website1_nevadaepro',
 'LOG_FILE': 'scrapy.log',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'website1_nevadaepro.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['website1_nevadaepro.spiders']}
2023-12-25 05:55:12 [scrapy.extensions.telnet] INFO: Telnet Password: a95199604f6e75e8
2023-12-25 05:55:12 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.logstats.LogStats']
2023-12-25 05:55:13 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy_selenium.SeleniumMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2023-12-25 05:55:13 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2023-12-25 05:55:13 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2023-12-25 05:55:16 [scrapy.crawler] INFO: Received SIGINT, shutting down gracefully. Send again to force 
2023-12-25 05:55:16 [twisted] CRITICAL: Unhandled error in Deferred:
2023-12-25 05:55:16 [twisted] CRITICAL: 
Traceback (most recent call last):
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
    result = g.send(result)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\scrapy\crawler.py", line 88, in crawl
    start_requests = iter(self.spider.start_requests())
  File "C:\Users\shubh\catalyst\website1_nevadaepro\website1_nevadaepro\spiders\nevadaepro_download_files.py", line 38, in start_requests
    driver.get(url)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 333, in get
    self.execute(Command.GET, {'url': url})
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 319, in execute
    response = self.command_executor.execute(driver_command, params)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 374, in execute
    return self._request(command_info[0], url, body=data)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\selenium\webdriver\remote\remote_connection.py", line 397, in _request
    resp = self._conn.request(method, url, body=body, headers=headers)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\request.py", line 78, in request
    return self.request_encode_body(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\request.py", line 170, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\poolmanager.py", line 375, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\util\retry.py", line 531, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\packages\six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 445, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\site-packages\urllib3\connectionpool.py", line 440, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 1347, in getresponse
    response.begin()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\http\client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\shubh\anaconda3\envs\scrapy\lib\socket.py", line 669, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None))
2023-12-25 05:57:08 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: website1_nevadaepro)
2023-12-25 05:57:08 [scrapy.utils.log] INFO: Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 20.0.1 (OpenSSL 1.1.1w  11 Sep 2023), cryptography 3.3.1, Platform Windows-10-10.0.22621-SP0
2023-12-25 05:57:18 [scrapy.utils.log] INFO: Scrapy 2.4.1 started (bot: website1_nevadaepro)
2023-12-25 05:57:18 [scrapy.utils.log] INFO: Versions: lxml 4.6.2.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 20.3.0, Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)], pyOpenSSL 20.0.1 (OpenSSL 1.1.1w  11 Sep 2023), cryptography 3.3.1, Platform Windows-10-10.0.22621-SP0
2023-12-25 05:57:18 [scrapy.crawler] INFO: Overridden settings:
{'BOT_NAME': 'website1_nevadaepro',
 'LOG_FILE': 'scrapy.log',
 'LOG_LEVEL': 'INFO',
 'NEWSPIDER_MODULE': 'website1_nevadaepro.spiders',
 'ROBOTSTXT_OBEY': True,
 'SPIDER_MODULES': ['website1_nevadaepro.spiders']}
2023-12-25 05:57:18 [scrapy.extensions.telnet] INFO: Telnet Password: 9303b65722f105a2
2023-12-25 05:57:18 [scrapy.middleware] INFO: Enabled extensions:
['scrapy.extensions.corestats.CoreStats',
 'scrapy.extensions.telnet.TelnetConsole',
 'scrapy.extensions.feedexport.FeedExporter',
 'scrapy.extensions.logstats.LogStats']
2023-12-25 05:57:20 [scrapy.middleware] INFO: Enabled downloader middlewares:
['scrapy.downloadermiddlewares.robotstxt.RobotsTxtMiddleware',
 'scrapy.downloadermiddlewares.httpauth.HttpAuthMiddleware',
 'scrapy.downloadermiddlewares.downloadtimeout.DownloadTimeoutMiddleware',
 'scrapy.downloadermiddlewares.defaultheaders.DefaultHeadersMiddleware',
 'scrapy.downloadermiddlewares.useragent.UserAgentMiddleware',
 'scrapy.downloadermiddlewares.retry.RetryMiddleware',
 'scrapy.downloadermiddlewares.redirect.MetaRefreshMiddleware',
 'scrapy.downloadermiddlewares.httpcompression.HttpCompressionMiddleware',
 'scrapy.downloadermiddlewares.redirect.RedirectMiddleware',
 'scrapy.downloadermiddlewares.cookies.CookiesMiddleware',
 'scrapy.downloadermiddlewares.httpproxy.HttpProxyMiddleware',
 'scrapy_selenium.SeleniumMiddleware',
 'scrapy.downloadermiddlewares.stats.DownloaderStats']
2023-12-25 05:57:20 [scrapy.middleware] INFO: Enabled spider middlewares:
['scrapy.spidermiddlewares.httperror.HttpErrorMiddleware',
 'scrapy.spidermiddlewares.offsite.OffsiteMiddleware',
 'scrapy.spidermiddlewares.referer.RefererMiddleware',
 'scrapy.spidermiddlewares.urllength.UrlLengthMiddleware',
 'scrapy.spidermiddlewares.depth.DepthMiddleware']
2023-12-25 05:57:20 [scrapy.middleware] INFO: Enabled item pipelines:
[]
2023-12-25 05:57:20 [scrapy.core.engine] INFO: Spider opened
2023-12-25 05:57:20 [scrapy.extensions.logstats] INFO: Crawled 0 pages (at 0 pages/min), scraped 0 items (at 0 items/min)
2023-12-25 05:57:20 [scrapy.extensions.telnet] INFO: Telnet console listening on 127.0.0.1:6023
2023-12-25 05:57:45 [scrapy.core.engine] INFO: Closing spider (finished)
2023-12-25 05:57:45 [scrapy.extensions.feedexport] INFO: Stored json feed (29 items) in: final.json
2023-12-25 05:57:47 [scrapy.statscollectors] INFO: Dumping Scrapy stats:
{'downloader/request_bytes': 15369,
 'downloader/request_count': 32,
 'downloader/request_method_count/GET': 32,
 'downloader/response_bytes': 388741,
 'downloader/response_count': 32,
 'downloader/response_status_count/200': 30,
 'downloader/response_status_count/301': 1,
 'downloader/response_status_count/302': 1,
 'elapsed_time_seconds': 25.64796,
 'finish_reason': 'finished',
 'finish_time': datetime.datetime(2023, 12, 25, 0, 27, 45, 834490),
 'item_scraped_count': 29,
 'log_count/INFO': 11,
 'response_received_count': 30,
 'robotstxt/request_count': 1,
 'robotstxt/response_count': 1,
 'robotstxt/response_status_count/200': 1,
 'scheduler/dequeued': 29,
 'scheduler/dequeued/memory': 29,
 'scheduler/enqueued': 29,
 'scheduler/enqueued/memory': 29,
 'start_time': datetime.datetime(2023, 12, 25, 0, 27, 20, 186530)}
2023-12-25 05:57:47 [scrapy.core.engine] INFO: Spider closed (finished)
